(require-package 'web-mode)

(defun web-mode-for-liquid-template ()
  (interactive)
  (web-mode)
  (web-mode-set-engine "django")
  (setq web-mode-markup-indent-offset 2)
  )

(defun web-mode-for-vue-template ()
  (interactive)
  (web-mode)
  (web-mode-set-engine "vue")
  (setq web-mode-style-padding 2)
  (setq web-mode-script-padding 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-markup-indent-offset 2)
  )

(defun web-mode-for-erb-template ()
  (interactive)
  (web-mode)
  (web-mode-set-engine "erb")
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-markup-indent-offset 2)
  )

(provide 'init-web-mode)
